from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import AppointmentViewSet

# Initialize the DefaultRouter
router = DefaultRouter()

# Register the AppointmentViewSet under the 'appointments' endpoint.
# When included in the main project URLs, this creates routes like:
# /api/v1/appointments/ (GET, POST)
# /api/v1/appointments/{pk}/ (GET, PUT, DELETE)
router.register(r'appointments', AppointmentViewSet, basename='appointment') 

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)), 
]