from rest_framework import serializers
from .models import Patient

class PatientSerializer(serializers.ModelSerializer):
    class Meta:
        model = Patient 
        fields = ('id', 'name', 'email', 'phone', 'created_at') 
        # These fields are generated by the system and cannot be set by the user
        read_only_fields = ('id', 'created_at')