# Generated by Django 5.2.1 on 2025-12-01 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_id', models.UUIDField(blank=True, help_text='The doctor assigned to the appointment.', null=True)),
                ('date', models.DateField(help_text='The scheduled date.')),
                ('time', models.TimeField(help_text='The scheduled time.')),
                ('patient', models.ForeignKey(help_text='The patient booking this appointment.', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
        ),
    ]
